@PackageTracker.Server_HostAddress = http://localhost:5081

GET {{PackageTracker.Server_HostAddress}}/packages/
Accept: application/json
###
GET {{PackageTracker.Server_HostAddress}}/package/{id}
Accept: application/json
###
POST {{PackageTracker.Server_HostAddress}}/package/create
Accept: application/json

{
  "packageId": "{{145663321}}",

}
